name: llama_cpp_dart
description: "Dart binding for llama.cpp --- high level wrappers for both Dart and Flutter"
version: 0.0.6+1
homepage: https://github.com/netdur/llama_cpp_dart

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^11.0.0
  path_provider: ^2.1.2
  system_info2: ^4.0.0

analyzer:
  exclude:
    - 'lib/src/llama_cpp.dart'

ffigen:
  name: 'llama_cpp'
  description: 'llama.cpp binding'
  output: 'lib/src/llama_cpp.dart'
  headers:
    entry-points:
      - 'llama.cpp/llama.h'
  compiler-opts:
    - '-Wno-nullability-completeness'
